### ISSUE TITLE
Input field validations

### ISSUE THREAD

**Issue by incrementcenter** [incrementcenter/EHA#3]
Գրել ֆունկցիա, որը որպես արգումենտ ստանում է string-ների զանգված (որոնք լինելու են input-ների name ատրիբուտի արժեքներ), և ստուգում է, արդյո՞ք տրված անունով input-ները դատարկ են, թե՞ ոչ:
Եթե կան դատարկները՝ վերադարձնում է զանգված, որը պարունակում է դրանց անունները:
Եթե բոլորը լցված են՝ վերադարձնում է true

**Comment by Ero7777** [comment]
I have already done my part!!!
